modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/trikzon/transparent/issues"
license = "MIT; Assets licensed as All Rights Reserved"

[[mods]]
modId = "transparent"
version = "${version}"
displayName = "Transparent"
authors = "Trikzon"
description = '''
Allows resource packs to make entities support transparency.
'''
#logoFile = ""

[[dependencies.transparent]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.transparent]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
