modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/trikzon/transparent/issues"

[[mods]]
modId="transparent"
version="${file.jarVersion}"
displayName="Transparent"
#updateJSONURL=""
displayURL="https://github.com/trikzon/transparent"
#logoFile=""
#credits=""
authors="Trikzon"
description='''
Allows resource packs to make entities support transparency.
'''

[[dependencies.transparent]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.transparent]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
